# Generated by Django 4.1.1 on 2022-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=30)),
                ("energy", models.FloatField(default=0.0)),
                ("protein", models.FloatField(default=0.0)),
                ("fat", models.FloatField(default=0.0)),
                ("carbohydrate", models.FloatField(default=0.0)),
                ("dietary_fiber", models.FloatField(default=0.0)),
                ("magnesium", models.FloatField(default=0.0)),
                ("vitamin_a", models.FloatField(default=0.0)),
                ("vitamin_d", models.FloatField(default=0.0)),
                ("vitamin_b6", models.FloatField(default=0.0)),
                ("folic_acid", models.FloatField(default=0.0)),
                ("vitamin_b12", models.FloatField(default=0.0)),
                ("tryptophan", models.FloatField(default=0.0)),
                ("dha_epa", models.FloatField(default=0.0)),
                ("classifier", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("energy", models.FloatField(default=0.0)),
                ("protein", models.FloatField(default=0.0)),
                ("fat", models.FloatField(default=0.0)),
                ("carbohydrate", models.FloatField(default=0.0)),
                ("dietary_fiber", models.FloatField(default=0.0)),
                ("magnesium", models.FloatField(default=0.0)),
                ("vitamin_a", models.FloatField(default=0.0)),
                ("vitamin_d", models.FloatField(default=0.0)),
                ("vitamin_b6", models.FloatField(default=0.0)),
                ("folic_acid", models.FloatField(default=0.0)),
                ("vitamin_b12", models.FloatField(default=0.0)),
                ("tryptophan", models.FloatField(default=0.0)),
                ("dha_epa", models.FloatField(default=0.0)),
            ],
        ),
    ]
