# Generated by Django 4.0.6 on 2022-09-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_food_category_food_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('energy', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('carbohydrate', models.FloatField(default=0.0)),
                ('dietary_fiber', models.FloatField(default=0.0)),
                ('magnesium', models.FloatField(default=0.0)),
                ('vitamin_a', models.FloatField(default=0.0)),
                ('vitamin_d', models.FloatField(default=0.0)),
                ('vitamin_b6', models.FloatField(default=0.0)),
                ('folic_acid', models.FloatField(default=0.0)),
                ('vitamin_b12', models.FloatField(default=0.0)),
                ('tryptophan', models.FloatField(default=0.0)),
                ('dha_epa', models.FloatField(default=0.0)),
            ],
        ),
    ]
