# Generated by Django 4.0.6 on 2022-12-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_efood'),
    ]

    operations = [
        migrations.AddField(
            model_name='efood',
            name='lang',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
