# Generated by Django 4.0.6 on 2022-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_efood_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='lang',
            field=models.CharField(default='ko', max_length=30),
        ),
    ]
