# Generated by Django 4.0.6 on 2022-08-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='consumption',
            old_name='post_id',
            new_name='post',
        ),
    ]
