# Generated by Django 4.0.6 on 2022-09-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('consumptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='supplementpost',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='supplementpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplementpost',
            name='supplement',
        ),
        migrations.CreateModel(
            name='SupplementConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumptions.supplementpost')),
                ('supplement', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.supplement')),
            ],
        ),
    ]
