# Generated by Django 4.0.6 on 2022-08-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0003_waterconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterconsumption',
            name='deprecated',
        ),
    ]
