# Generated by Django 4.0.6 on 2022-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0005_remove_consumption_img1_remove_consumption_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
