# Generated by Django 4.0.6 on 2022-08-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_at'),
        ('consumptions', '0006_alter_foodimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
