# Generated by Django 4.0.6 on 2022-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0007_alter_foodimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
