# Generated by Django 4.0.6 on 2022-08-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0009_alter_foodimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
