# Generated by Django 4.0.6 on 2022-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0010_alter_foodimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
