# Generated by Django 4.0.6 on 2022-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=30)),
                ('type1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type11', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
