# Generated by Django 4.0.6 on 2022-10-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='type12',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
